refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{h({l})} {m}{n}"
  file:
    kind: rolling_file
    path: "logs/ros2.log"
    encoder:
      pattern: "{d} - {m}{n}"
  rosout:
    kind: file
    path: "logs/rosout.log"
    append: true
root:
  level: info
  appenders:
    - stdout
    - file
loggers:
  ros2_client:
    level: warn
    appenders:
      - stdout
      - file
